### ISSUE TITLE
usage of page-name for splitLanding pages

### ISSUE THREAD

**Issue by andreaschu** [christian-fr/zofarCalendarSuite#2]
It seems that the splitLanding page is generated on some place with **EPISODE_TYPE_STR** (e.g. sco) and on the other place with **PAGE_NAME_STARTSWITH** (e.g. scoa). This leads to transition-errors in the output.xml.
Here are the usages within the [zcs/data/xmlgen.py](https://github.com/christian-fr/zofarCalendarSuite/blob/0af72af250428baa01e380abfc4cea52b51e50dc/zcs/data/xmlgen.py): 

1. PAGE_NAME_STARTSWITH (line: 1073)
https://github.com/christian-fr/zofarCalendarSuite/blob/0af72af250428baa01e380abfc4cea52b51e50dc/zcs/data/xmlgen.py#L1073

2. PAGE_NAME_STARTSWITH (line: 715)
https://github.com/christian-fr/zofarCalendarSuite/blob/0af72af250428baa01e380abfc4cea52b51e50dc/zcs/data/xmlgen.py#L715

3. input_pages_startswith (EPISODE_TYPE_STR?) (lines: 746/ 754)
https://github.com/christian-fr/zofarCalendarSuite/blob/0af72af250428baa01e380abfc4cea52b51e50dc/zcs/data/xmlgen.py#L746
https://github.com/christian-fr/zofarCalendarSuite/blob/0af72af250428baa01e380abfc4cea52b51e50dc/zcs/data/xmlgen.py#L754

**Comment by christian-fr** [comment]
I think that any **splitLanding**-page that only use the _EPISODE_TYPE_STR_ was manually added.

I modified the xmlgen.py so that any page it generates automatically gets a comment added to indicate its origin:

![grafik](https://user-images.githubusercontent.com/42959832/182193196-a659f4ff-52ea-4fb5-9260-0d938e49966d.png)

**Comment by andreaschu** [comment]
So just to understand this right: 
In the automation it is always used PAGE_NAME_STARTSWITH, right? So it is in this case `doca` and not `doc`.
Where are these pages 'used' in the automation and in what way. 
How should they be named: `splitLanding_doca` or `splitLanding_doca01`?

**Comment by christian-fr** [comment]
We will now use only the `EPISODE_TYPE_STR` for this purpose.

So both the `defaultLanding_XXX` as well as the `splitLanding_XXX` will use `EPISODE_TYPE_STR` for their UIDs: 
it is therefore `splitLanding_doc`, `defaultLanding_doc`, `splitLanding_voc`, `defaultLanding_voc`, etc.
