### ISSUE TITLE
using variables within code

### ISSUE THREAD

**Issue by andreaschu** [christian-fr/zofarCalendarSuite#3]
The use of the variables for the range of monthpicker (monthpickerstartwith... ) are coded in the xml-generator.
https://github.com/christian-fr/zofarCalendarSuite/blob/0af72af250428baa01e380abfc4cea52b51e50dc/zcs/data/xmlgen.py#L374-L406

To me as a zofar programmer it is risky. When the name of the variable is changed, the generated xml doesn't work correct.

**Comment by christian-fr** [comment]
I think this does should not be a problem, as `monthpickerepisodestart` and `monthpickerepisodeend` are auxiliary variables that are computed for the currently active episode.

Their main feature is that they provide _timestamp strings that are formatted for the monthpicker_ and have a fallback: they are set to calendar start or calendar end.

So we can just as easily compute and use them in a Zofar monthpicker question - or we just don't and use none or another variable for monthpicker range. We can determine that in the QML question via its attributes.

What I see as a more severe problem is the _fallback-option_: this is dependent on the names of the calendar range variables, which are right now hardcoded in the Python code. But I don't know how to change that elegantly.

**Comment by andreaschu** [comment]
Okay, I think I didn't fully understood the matter of this auxiliary variables. For it is only to match the format of the dates to the monthpicker it is okay to have it hard coded in the automation. 
But we have to communicate or safe this bit to zofar users so that it transparent for new zofar programmers.

**Comment by christian-fr** [comment]
the documentation need have been noted here #9 , issue will be closed
