### ISSUE TITLE
trigger on defaultLanding-pages

### ISSUE THREAD

**Issue by andreaschu** [christian-fr/zofarCalendarSuite#5]
The automation could create a trigger on defaultLanding_[MODULE] pages to redirect on to module starting page or to manualBackwardsBlock_[MODULE] so that it doesn't has to be added by hand.

```
		<zofar:triggers>
			<zofar:action command="navigatorBean.redirect('manualBackwardsBlock_mpla008')" onExit="false"/>
		</zofar:triggers>
```

**Comment by christian-fr** [comment]
We shall leave this out of the automation and set the entry into modules manually.
